version: 2
updates:
  - package-ecosystem: "maven"
    directory: "vietsneaker-server/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(maven):"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
    groups:
      dev-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "vietsneaker-ui/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps(npm):"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    groups:
      dev-dependencies:
        patterns:
          - "*"
