name: Docker image

on:
  push:
    branches:
      - main
      - "release*"

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push vietsneaker-server image
        uses: docker/build-push-action@v5
        with:
          context: ./vietsneaker-server
          file: ./vietsneaker-server/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vietsneaker-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vietsneaker-server:${{ github.sha }}

      - name: Build and push vietsneaker-web image
        uses: docker/build-push-action@v5
        with:
          context: ./vietsneaker-ui
          file: ./vietsneaker-ui/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vietsneaker-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vietsneaker-web:${{ github.sha }}
